name: Build FIO Binaries

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        goos: [windows, freebsd, linux, darwin]
        goarch: [amd64, 386]
        exclude:
          - goarch: 386
            goos: darwin
        include:
          - goos: windows
            goarch: 386
          - goos: windows
            goarch: amd64
          - goos: windows
            goarch: arm64
          - goos: windows
            goarch: arm
            goarm: 7
          - goos: darwin
            goarch: arm64
          - goos: linux
            goarch: arm
            goarm: 7
          - goos: linux
            goarch: arm64
          - goos: linux
            goarch: riscv64
          - goos: linux
            goarch: mips64
          - goos: linux
            goarch: mips64le
          - goos: linux
            goarch: mipsle
          - goos: linux
            goarch: mips
          - goos: linux
            goarch: ppc64
          - goos: linux
            goarch: ppc64le
          - goos: freebsd
            goarch: arm64
          - goos: freebsd
            goarch: arm
            goarm: 7
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Dockcross
        run: |
          docker run --rm dockcross/linux-${{ matrix.goarch }} > dockcross-${{ matrix.goarch }}
          chmod +x dockcross-${{ matrix.goarch }}

      - name: Download and extract FIO
        run: |
          wget https://github.com/axboe/fio/archive/refs/tags/fio-3.39.zip
          unzip fio-3.39.zip
          mv fio-fio-3.39 fio-src

      - name: Build FIO for ${{ matrix.goos }}-${{ matrix.goarch }}
        run: |
          cd fio-src
          make clean
          ../dockcross-${{ matrix.goarch }} bash -c "make CC=gcc LDFLAGS='-static'"
          mkdir -p ../bin
          cp fio ../bin/fio-${{ matrix.goos }}-${{ matrix.goarch }}

      - name: Upload binaries as artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fio-binaries
          path: bin/*